# Configuration for Release Drafter - https://github.com/toolmantim/release-drafter

name-template: v$NEXT_PATCH_VERSION
tag-template: v$NEXT_PATCH_VERSION
categories:
  - title: "🚀 Enhancement"
    label: "feature ✨"

  - title: "🌐 Translations"
    label: "translation 🌍"

  - title: "🐛 Bug Fix"
    label: "bug 🐛"

  - title: "📝 Documentation"
    label: "documentation 📖"

  - title: "💅 Refactor"
    label: "refactor ♻️"

  - title: "🏠 Internal"
    label: "internal 🏠"

  - title: "🔧 Tooling"
    label: "tooling 🔧"

  - title: "📦 Dependencies"
    label: "dependencies 📦"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- No changes"
template: |
  ***
  ### ⚡️ Changes
  $CHANGES
  ***
  ### 🦄 Contributors
  Thank you $CONTRIBUTORS for the contributions! 🏆
  ***
